# conda env create --file environment.yml
name: car_prices
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pandas-profiling
  - fs
  - jupyterlab
  - jupyter
  - pathlib
  - pip
  - pyprojroot
  - python=3.9
  - pip:
    - pyhere
    